# Generated by Django 4.2.5 on 2023-10-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='ImageName',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregister',
            name='pic',
            field=models.ImageField(default=0, upload_to='../static/img'),
            preserve_default=False,
        ),
    ]
