# Generated by Django 4.2.5 on 2023-10-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_userregister_imagename_alter_userregister_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='pic',
            field=models.ImageField(upload_to='auth_app/static/img/'),
        ),
    ]
