name : CI Pipeline

on : 
  push :
    branches :
      - python
      - fastapi

jobs:
  test:
    run-on: ubunto-latest

    steps:
    -  name : Checkout code 
       uses: actions/checkout@v3

    - name : Set up Python 
      uses : actions/setup-python@v4
      with : 
        python-version : '3.10'

    - name : Install dependancies
      run : | 
        pip Install -r requirements.txt 

    - name : Run test
      run : |
        pytest


