# Generated by Django 4.2.7 on 2023-11-03 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_app0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_heaading', models.CharField(max_length=200)),
                ('post_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajax_app0.mypost')),
            ],
        ),
    ]
