# Generated by Django 4.2.5 on 2023-10-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_app', '0002_remove_post_id_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
