# Generated by Django 4.2.5 on 2023-10-31 02:35

from django.db import migrations, models

def set_default_post_id(apps,shema_editor):
    Post = apps.get_model('ajax_app','Post')
    for post in Post.objects.all():
        post.post_id = post.id
        post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ajax_app', '0004_post_id_alter_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.AutoField(default=0, primary_key=True),
        ),
        migrations.RunPython(set_default_post_id),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
    ]
